spring:
  application:
    name: batch
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations:
        - classpath:/initialize-database.sql
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: repeatable_read
      schema: classpath:/initialize-database.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.batch.model
  configuration:
      map-underscore-to-camel-case: true